### ISSUE TITLE
Device displayed as Faucet and not Sprinkler

### ISSUE THREAD

**Issue by funkyremi** [goedh452/homebridge-http-sprinkler#14]
<img width="800" alt="homekit-accessories" src="https://user-images.githubusercontent.com/4487178/71561116-8ab55780-2a72-11ea-83ab-7be8cac5ab25.png">

**Comment by goedh452** [comment]
Hi, can you post the part of the config for these accessories?

**Comment by funkyremi** [comment]
Hi,
I mean when I set the config as described in the readme, I get a "Faucet" icon in home app and not a "Sprinkler" icon (you can see the difference in the image).

```
"accessories": [
     {
       "accessory": "HttpSprinkler",
       "name": "HTTP Sprinkler",
       "onUrl": "http://myurl.com/on",
       "offUrl": "http://myurl.com/off"
     }
]
```

I tried to change the "icon" parameter but none of them is a sprinkler icon.

**Comment by goedh452** [comment]
I understand the problem. Homekit is not very willing to change an accessory once it has been added. Could you try the following:
Remove the sprinkler from the config
Restart homebridge
Check Home app to see that accessory has been removed
Add the item to the config with the line "icon": 1,
Restart homebridge

Hopefully the accessory is added as a sprinkler now.

**Comment by funkyremi** [comment]
Awesome thank you 😊 🙏
