### ISSUE TITLE
Time keeps resetting 

### ISSUE THREAD

**Issue by tumekee** [goedh452/homebridge-http-sprinkler#15]
Hi Awesome plugin , the time count down appears always reset , seams to happening with polling or when the app is closed and opened again. i saw in another issue "Problems by setting the jsonPath?? :)" the it was mentioned , but was told it was an apple problem, iv used sonoffs ( stopped now they keep catching on fire lol )  in the past and not had this issue which means it probably not an apple probably an issue with the plugin. any ideas ? thanks !

**Comment by tumekee** [comment]
figured it out more info :)

**Comment by goedh452** [comment]
Hi tumekee,
I'm aware of the issue but am just not a goog coder enough to figure it out. Since in the background the correct timer is used for stopping the sprinkler it works for mee. When I've some time I'll look into it.
