### ISSUE TITLE
Can 2 Sprinkler units be setup with the one instance of this plugin?

### ISSUE THREAD

**Issue by SeanHama** [goedh452/homebridge-http-sprinkler#17]
Hi, I have 2 sprinklers, it seems only 1 sprinkler can be support, can you pls confirm how do setup?

**Comment by goedh452** [comment]
That is correct. The instance only supports 1 sprinkler. If you want to add 2, just add the module twice in the config.

**Comment by SeanHama** [comment]
To confirm, I just copy and paste the config in the same config.json or do I need to do more work?

>

**Comment by goedh452** [comment]
That is correct. Only change the URL's.

**Comment by SeanHama** [comment]
Perfect, I’ll give that a go

Excuse any typos, email sent from my mobile device.
